spring:
  datasource:
    username: root
    password: 123456Aa.
    url: jdbc:mysql://43.136.75.221:3306/ai
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8085
  servlet:
    context-path: /
  address: 0.0.0.0


#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
