# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhujiemianui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1852, 1060)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 40, 761, 551))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(970, 50, 31, 21))
        self.pushButton_9.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_9.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setObjectName("pushButton_9")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(450, 510, 381, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.functionBT = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.functionBT.setFont(font)
        self.functionBT.setStyleSheet("#functionBT{\n"
"    border:none;\n"
"}\n"
"#functionBT:focus{\n"
"    \n"
"    color: rgb(158, 158, 158);\n"
"}")
        self.functionBT.setObjectName("functionBT")
        self.horizontalLayout.addWidget(self.functionBT)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.zuheydBT = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.zuheydBT.setFont(font)
        self.zuheydBT.setStyleSheet("#zuheydBT{\n"
"    border:none;\n"
"}\n"
"#zuheydBT:focus{\n"
"    \n"
"    \n"
"    color: rgb(158, 158, 158);\n"
"}")
        self.zuheydBT.setObjectName("zuheydBT")
        self.horizontalLayout.addWidget(self.zuheydBT)
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.gerenBT = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gerenBT.setFont(font)
        self.gerenBT.setStyleSheet("#gerenBT{\n"
"    border:none;\n"
"}\n"
"#gerenBT:focus{\n"
"    \n"
"    \n"
"    color: rgb(158, 158, 158);\n"
"}")
        self.gerenBT.setObjectName("gerenBT")
        self.horizontalLayout.addWidget(self.gerenBT)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(300, 90, 651, 391))
        self.widget.setObjectName("widget")
        self.shendunBT = QtWidgets.QPushButton(self.widget)
        self.shendunBT.setGeometry(QtCore.QRect(40, 40, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.shendunBT.setFont(font)
        self.shendunBT.setObjectName("shendunBT")
        self.fuwochengBT = QtWidgets.QPushButton(self.widget)
        self.fuwochengBT.setGeometry(QtCore.QRect(250, 40, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.fuwochengBT.setFont(font)
        self.fuwochengBT.setObjectName("fuwochengBT")
        self.yintiBT = QtWidgets.QPushButton(self.widget)
        self.yintiBT.setGeometry(QtCore.QRect(470, 40, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.yintiBT.setFont(font)
        self.yintiBT.setObjectName("yintiBT")
        self.yalingBT = QtWidgets.QPushButton(self.widget)
        self.yalingBT.setGeometry(QtCore.QRect(40, 130, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.yalingBT.setFont(font)
        self.yalingBT.setObjectName("yalingBT")
        self.zzyalingBT = QtWidgets.QPushButton(self.widget)
        self.zzyalingBT.setGeometry(QtCore.QRect(250, 130, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.zzyalingBT.setFont(font)
        self.zzyalingBT.setObjectName("zzyalingBT")
        self.cetaituiBT = QtWidgets.QPushButton(self.widget)
        self.cetaituiBT.setGeometry(QtCore.QRect(470, 130, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cetaituiBT.setFont(font)
        self.cetaituiBT.setObjectName("cetaituiBT")
        self.yangwoqizuoBT = QtWidgets.QPushButton(self.widget)
        self.yangwoqizuoBT.setGeometry(QtCore.QRect(250, 220, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.yangwoqizuoBT.setFont(font)
        self.yangwoqizuoBT.setObjectName("yangwoqizuoBT")
        self.chexiangkaiheBT = QtWidgets.QPushButton(self.widget)
        self.chexiangkaiheBT.setGeometry(QtCore.QRect(470, 220, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chexiangkaiheBT.setFont(font)
        self.chexiangkaiheBT.setObjectName("chexiangkaiheBT")
        self.tunqiaoBT = QtWidgets.QPushButton(self.widget)
        self.tunqiaoBT.setGeometry(QtCore.QRect(40, 220, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tunqiaoBT.setFont(font)
        self.tunqiaoBT.setObjectName("tunqiaoBT")
        self.xiaduntingBT = QtWidgets.QPushButton(self.widget)
        self.xiaduntingBT.setGeometry(QtCore.QRect(40, 310, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.xiaduntingBT.setFont(font)
        self.xiaduntingBT.setObjectName("xiaduntingBT")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setGeometry(QtCore.QRect(470, 310, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.juanfuBT = QtWidgets.QPushButton(self.widget)
        self.juanfuBT.setGeometry(QtCore.QRect(250, 310, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.juanfuBT.setFont(font)
        self.juanfuBT.setObjectName("juanfuBT")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(310, 80, 661, 401))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(560, 140, 91, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tuichuBT = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tuichuBT.setFont(font)
        self.tuichuBT.setStyleSheet("#tuichuBT{\n"
"    border:none;\n"
"}\n"
"#tuichuBT:focus{\n"
"    \n"
"    \n"
"    color: rgb(158, 158, 158);\n"
"}")
        self.tuichuBT.setObjectName("tuichuBT")
        self.verticalLayout.addWidget(self.tuichuBT)
        self.line_2 = QtWidgets.QFrame(self.widget_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.fanhuiBT = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fanhuiBT.setFont(font)
        self.fanhuiBT.setStyleSheet("#fanhuiBT{\n"
"    border:none;\n"
"}\n"
"#fanhuiBT:focus{\n"
"    \n"
"    color: rgb(158, 158, 158);\n"
"}")
        self.fanhuiBT.setObjectName("fanhuiBT")
        self.verticalLayout.addWidget(self.fanhuiBT)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(570, 20, 72, 15))
        self.label_3.setObjectName("label_3")
        self.yonghuminglb = QtWidgets.QLabel(self.widget_3)
        self.yonghuminglb.setGeometry(QtCore.QRect(570, 70, 72, 15))
        self.yonghuminglb.setText("")
        self.yonghuminglb.setObjectName("yonghuminglb")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 551, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(922, 50, 41, 28))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../.designer/backup/icons/disexpend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(940, 50, 31, 21))
        self.pushButton_16.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_16.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/disexpend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(320, 79, 650, 421))
        self.widget_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.shendunCB = QtWidgets.QCheckBox(self.widget_6)
        self.shendunCB.setGeometry(QtCore.QRect(50, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.shendunCB.setFont(font)
        self.shendunCB.setObjectName("shendunCB")
        self.fuwochengCB = QtWidgets.QCheckBox(self.widget_6)
        self.fuwochengCB.setGeometry(QtCore.QRect(200, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.fuwochengCB.setFont(font)
        self.fuwochengCB.setObjectName("fuwochengCB")
        self.yintiCB = QtWidgets.QCheckBox(self.widget_6)
        self.yintiCB.setGeometry(QtCore.QRect(350, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.yintiCB.setFont(font)
        self.yintiCB.setObjectName("yintiCB")
        self.yalingCB = QtWidgets.QCheckBox(self.widget_6)
        self.yalingCB.setGeometry(QtCore.QRect(520, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.yalingCB.setFont(font)
        self.yalingCB.setObjectName("yalingCB")
        self.zzyalingCB = QtWidgets.QCheckBox(self.widget_6)
        self.zzyalingCB.setGeometry(QtCore.QRect(40, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.zzyalingCB.setFont(font)
        self.zzyalingCB.setObjectName("zzyalingCB")
        self.cetaituiCB = QtWidgets.QCheckBox(self.widget_6)
        self.cetaituiCB.setGeometry(QtCore.QRect(200, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cetaituiCB.setFont(font)
        self.cetaituiCB.setObjectName("cetaituiCB")
        self.tunqiaoCB = QtWidgets.QCheckBox(self.widget_6)
        self.tunqiaoCB.setGeometry(QtCore.QRect(350, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tunqiaoCB.setFont(font)
        self.tunqiaoCB.setObjectName("tunqiaoCB")
        self.yangwoqizuoCB = QtWidgets.QCheckBox(self.widget_6)
        self.yangwoqizuoCB.setGeometry(QtCore.QRect(510, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yangwoqizuoCB.setFont(font)
        self.yangwoqizuoCB.setObjectName("yangwoqizuoCB")
        self.cexiangkaiheCB = QtWidgets.QCheckBox(self.widget_6)
        self.cexiangkaiheCB.setGeometry(QtCore.QRect(40, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cexiangkaiheCB.setFont(font)
        self.cexiangkaiheCB.setObjectName("cexiangkaiheCB")
        self.xiaduntingCB = QtWidgets.QCheckBox(self.widget_6)
        self.xiaduntingCB.setGeometry(QtCore.QRect(190, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.xiaduntingCB.setFont(font)
        self.xiaduntingCB.setObjectName("xiaduntingCB")
        self.juanfuCB = QtWidgets.QCheckBox(self.widget_6)
        self.juanfuCB.setGeometry(QtCore.QRect(350, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.juanfuCB.setFont(font)
        self.juanfuCB.setObjectName("juanfuCB")
        self.yalingyinglaCB = QtWidgets.QCheckBox(self.widget_6)
        self.yalingyinglaCB.setGeometry(QtCore.QRect(510, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yalingyinglaCB.setFont(font)
        self.yalingyinglaCB.setObjectName("yalingyinglaCB")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setGeometry(QtCore.QRect(150, 260, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.querenBT = QtWidgets.QPushButton(self.widget_6)
        self.querenBT.setGeometry(QtCore.QRect(120, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.querenBT.setFont(font)
        self.querenBT.setObjectName("querenBT")
        self.qinglingBT = QtWidgets.QPushButton(self.widget_6)
        self.qinglingBT.setGeometry(QtCore.QRect(390, 330, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.qinglingBT.setFont(font)
        self.qinglingBT.setObjectName("qinglingBT")
        self.spinBox = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox.setGeometry(QtCore.QRect(420, 270, 46, 22))
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1852, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_9.clicked.connect(MainWindow.close)
        self.pushButton_16.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.functionBT.setText(_translate("MainWindow", "传统运动"))
        self.zuheydBT.setText(_translate("MainWindow", "组合运动"))
        self.gerenBT.setText(_translate("MainWindow", "个人界面"))
        self.shendunBT.setText(_translate("MainWindow", "深蹲"))
        self.fuwochengBT.setText(_translate("MainWindow", "俯卧撑"))
        self.yintiBT.setText(_translate("MainWindow", "引体向上"))
        self.yalingBT.setText(_translate("MainWindow", "哑铃"))
        self.zzyalingBT.setText(_translate("MainWindow", "站姿哑铃"))
        self.cetaituiBT.setText(_translate("MainWindow", "侧抬腿"))
        self.yangwoqizuoBT.setText(_translate("MainWindow", "仰卧起坐"))
        self.chexiangkaiheBT.setText(_translate("MainWindow", "侧向开合"))
        self.tunqiaoBT.setText(_translate("MainWindow", "臀桥"))
        self.xiaduntingBT.setText(_translate("MainWindow", "下蹲挺"))
        self.pushButton_14.setText(_translate("MainWindow", "哑铃硬拉"))
        self.juanfuBT.setText(_translate("MainWindow", "卷腹"))
        self.tuichuBT.setText(_translate("MainWindow", "退出"))
        self.fanhuiBT.setText(_translate("MainWindow", "返回"))
        self.label_3.setText(_translate("MainWindow", "用户名："))
        self.shendunCB.setText(_translate("MainWindow", "深蹲"))
        self.fuwochengCB.setText(_translate("MainWindow", "俯卧撑"))
        self.yintiCB.setText(_translate("MainWindow", "引体向上"))
        self.yalingCB.setText(_translate("MainWindow", "哑铃"))
        self.zzyalingCB.setText(_translate("MainWindow", "站姿哑铃"))
        self.cetaituiCB.setText(_translate("MainWindow", "侧抬腿"))
        self.tunqiaoCB.setText(_translate("MainWindow", "臀桥"))
        self.yangwoqizuoCB.setText(_translate("MainWindow", "仰卧起坐"))
        self.cexiangkaiheCB.setText(_translate("MainWindow", "侧向开合"))
        self.xiaduntingCB.setText(_translate("MainWindow", "下蹲挺"))
        self.juanfuCB.setText(_translate("MainWindow", "卷腹"))
        self.yalingyinglaCB.setText(_translate("MainWindow", "哑铃硬拉"))
        self.label_2.setText(_translate("MainWindow", "所选动作每个各做(单位为秒)："))
        self.querenBT.setText(_translate("MainWindow", "确定"))
        self.qinglingBT.setText(_translate("MainWindow", "清零"))

import resource_rc
